### ISSUE TITLE
CompileContext::get_string_table won't work

### ISSUE THREAD

**Issue by steveklabnik** [Robbepop/cionc#6]
Yeah, your comment is correct. Like, you can't do this, because the borrow from borrow_mut is gonna go away at the end of the function.

In general, RefCell is a pretty niche structure that you should only use when you absolutely have to. I'm not sure if you absolutely have to here or not.

**Comment by Robbepop** [comment]
So how can I implement this in the way Rust should be used? I need a central structure to manage these things as multiple different entities (that may work and life at the same time) are using them. (e.g. ErrorHandler)

**Comment by steveklabnik** [comment]
It's not super clear to me, because parsers are my personal kryptonite ;)

Something like this might be worth a post on users.rust-lang.org.

**Comment by Robbepop** [comment]
Thank you for pointing that out to me. I will post my structural problems there. =)
